name: flutter_food
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  provider: ^6.1.2
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  google_fonts: ^6.1.0
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cartLoader.json
